name: Validate Azure Connection

# This workflow runs on any push to the main branch
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  validate-connection:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Log in to Azure using the secret
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Run a command to validate the connection
      - name: List resources in resource group
        run: |
          echo "Successfully logged in to Azure!"
          echo "Listing resources in resource group to validate connection..."
          az group list --output table
          echo "Validation complete."
          
      # Step 3: Log out of Azure (good practice)
      - name: Log out
        run: |
          az logout
          az account clear
